version: '3.8'

services:
  database:
    image: mariadb:10.6
    container_name: mariadb_db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123
      MARIADB_DATABASE: restaurante_db
      MARIADB_USER: listi
      MARIADB_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: 
      context: ./backend
    container_name: spring_backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/restaurante_db
      SPRING_DATASOURCE_USERNAME: listi
      SPRING_DATASOURCE_PASSWORD: 123
    volumes:
      # Mapeo de código fuente y caché de Maven para desarrollo
      - ./backend:/app 
      - ~/.m2:/root/.m2

  frontend:
    build: 
      context: ./frontend
    container_name: svelte_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      # URL del Backend usando el nombre del servicio de Docker
      VITE_API_URL: http://backend:8080/api 
    volumes:
      - ./frontend:/app 

volumes:
  db_data: